language: node_js
node_js:
- stable
addons:
  sauce_connect: true
before_script:
- npm install -g gulp bower
- npm install
- bower install
script: npm test
env:
  global:
  - secure: HL8rn7KnK2Cfhgnn7IWm4o9EMIaPucPCqkmW4PingqAIL8fSJW3sC2tu3nlFaKAYdnAZ1BkKga9BNaFeX9umKgY7RnwNN6M7A1w8PwYocpGxM5qx6Aun1Y+uqQWs679FZYgYOR1W8z+gOprOSw5Rkyhexelk78B1Y3aM5URpzgxtjlSlndUEHwyoFSU6ZnzPKAZb4E8ioOR6D+GZE41dtkzVCbLN3Yp3lhm7sM0+GzUDnFlrnCtfR0rA5J5ciNnQbSwvadpkoN6CXKBGmVRvwc4WAQvofInHf9/nLlK/9oPFCVJsfCYjTAMkm5ORP+qG2v8/M+CtdXzd0UPZvSu/y1+gBilkPkpKupNfY9vlu43Q3dojEP6uvK656CYbPlLu49e8y19TfPP27oY0iHmpcXwT6Vv4pxjwny1RFegNmRB8hltYVT0Jb25tIC74kWGvSyzO6MmaiBDfCag11bpTFZMGgIUMTHT8wCknK0ydE6T1mp6rgdEk6LAvpBd1Djyr6knX6vtl7Pdmujl/YZGaxo8it6TsHaEObPHuzlLHQi12uwM+s5aQezdFpZQq/BDy+uyS/iS3w4kCsn17TMRrN39ebq71P4Sny4RfkwbyFW/qNA3LYicuwzkBbSfM+3lLyJ1Yl5Xo1mdPmI5XFUojZCpyKd347dqlAbDdLimGxQ4=
  - secure: Q0yG1XM+Ir7xsNNK6DmFrqNMUH3LYkRNviqkbjT2/WYk7YUXAbasfUdTJ0wUVSN5DzFrtif8Hkrue8TPZaq1RJlbyi/3uvMEMV4IdmgKsq85rXoiLsf7rhwlWG5DVqIrIAFNmBiAFRY6kz2mPpvsaa+DL9v6xcbYGHwWgvtvMwmbkEpUtMPN6WNH48A0cFlakPHC00cieVR3vh2Vj4rofZfGHypS+wyUgLvzeqHqjQm2yYzymbYQxnB+W++6eeDVhwaQ4qmwW8Y5dyb98uN124WIoiYz8ZjJETHnb9a0mhfGnadFBJK6u3p55CuF2DrMwoD1a0hg9ZxmuHii8l4OHqOegDOA2DU7rWLSYO21x38TGRE1emOW3xpLIO9UVfT9T99oH2X7cgdB1Cb/6X5dMkKOZtdEFE58vdt0Za98aFsbTj1/WSPXZASDIihFaa6KJ+YBMUnU74tzcUq1TNfE8eL+1fEoYqf1GWAcX983PoW6F/MJCqTnBpXOAvSWpY19X5y3iNfLBlEETn+EtjLRLkdUohQjFEov06LjjOUMV4+GUeBum3oY6CsCnhLr/YMnDELlicn78tHUEBX1PW5G8g0jplZa+TPmlX3xch0sKfB5m80Qb97KfoVrLUuVhp6Xv3icBSOhz+TuKfNlNbqdJOfEbWqZmKpbpAi/UyjhS5I=
